### PR TITLE
Switch to simperium

### PR DESCRIPTION
**Pull request by atomicules**
PR to disucss / track switching to the Simperium API.

A fair amount had changed on master since the original simperium branches so this a new branch off master merging in the Simperium stuff.

Main comments:

- [x] Tests pass in Python 2
- [x] Python 3 compatibilty needs adding back in
- [x] Auth stuff needs adding back in (we have a way to do this now)
- [x] Tidying up to do
- [x] Performance still ok?

I'm very on/off as far as having time to spend on this, but am planning on doing this for October.

### CODE REVIEW

**Comment by atomicules** [comment]
Quick notes on testing "performance".

Fetching all my notes (a few!):

Using Simperium:

```
>>> start_time = time.time(); notes, status = sn.get_note_list();print("--- %s seconds ---" % (time.time() - start_time))                                                                                               │                                                                                                                                   
--- 19.0744287968 seconds ---
```

Old api:

```
>>> start_time = time.time(); notes, status = sn.get_note_list();print("--- %s seconds ---" % (time.time() - start_time))
--- 30.8318629265 seconds --- 
```

I doubt it really is faster because we are fetching all the notes content now as well, but I'm glad it's not lots slower.

**Comment by atomicules** [comment]
Done a bit of the tidying up. But needs more.

**Comment by atomicules** [comment]
I can't get merging of notes to work 😢 . It's supposed to work. Might have to take a bit to figure something out for this.

**Comment by cbarrett** [comment]
Hello, long time listener, first time caller. Is there anything I can do to help? I use this to back up my notes and want to contribute back.

**Comment by atomicules** [comment]
@cbarrett Hey. Thanks. I don't know... at the moment I can't get the:

> strings have automatic conflict resolution

bit to work. An update at the moment via simplenote.py always overwrites the remote version. It doesn't merge in changes made remotely. This is odd, because if I do it via curl on the command line it works as expected.

I _suspect_ it maybe unicode related... or something like that... i.e. it's not seeing what gets posted via urllib2 as a "string". Well, enough to update the remote, but note enough to merge stuff.

Still digging. This is the main stumbling block at the moment.

**Comment by atomicules** [comment]
@cbarrett Well... you helped just by making me look at this again. It was just me being an idiot:

5f1a9adf7e8775b86d00d0ce35ef0b843863d77c

Ok. Just tidying up to do. And then more testing. That would be good for people to help out with. Aim is for this to be a drop in replacement... i.e. if you use simplenote.py you just carry on using it and there are no changes required. But reality could be different.

**Comment by atomicules** [comment]
I'm currently doing some testing with simplenote.vim to get a feel for breakage and what other compatibility fields I need to add.

I think the main difference is I will need to switch `str()` uses to `unicode()` in simplenote.vim, but that is probably the right thing to do anyway.

**Comment by atomicules** [comment]
As far as I can tell, excepting one tiny change, this works as a drop in replacement in simplenote.vim.

Main issues:

- `since` no longer works. I used that a lot... so I'll probably finally have to look at some form of caching instead
- Need to tidy up commits / code
- For some reason the get a list of notes test in simplenote.vim fails with 10 != 12... don't understand why yet or if it's that critical.

**Comment by cbarrett** [comment]
Awesome! I'll try running this with my backup script and let you know.

**Comment by atomicules** [comment]
That'll probably do for an initial 2.0.0 Simperium release. Can then tidy up afterwards.

However... I am probably going to rebase this branch and force push it because the commits and commit messages are a bit crappy.

**Pull request merged**
