### PR TITLE
Using same instance for tests so they fail less because of Simplenote se...

### PR DESCRIPTION
**Pull request by sickmartian**
Hi Daniel,

I have been using your simplenote.py library for some time now for my sublime text 2 plugin, it has been working great so far, so thanks for your work :)

Now I wanted to adapt my plugin for sublime text 3, which uses python 3 as language instead of python 2, so I forked your project and started adapting it to work on python 3. First thing I had to do was re-work a little the tests since Simplenote seems to be rejecting the strategy of logging for each request that they were using before. I added also a delay between the operations so Simplenote doesn't reject the requests. Hope this is alright. I will soon send a pull request for the python 3 version (which is based on this commit).

after delay
before delay

Regards and happy holidays.

### CODE REVIEW

**Comment by atomicules** [comment]
Hi, sorry, I've been off github for a few weeks so missed this until now. I'll have to have a think about this. I like the idea of Python 3 compatibility as long as it still works fine in Python 2.

With regards to the tests and Travis, I got rid of the testing under multiple versions of Python because I thought it could be causing test failures due to trying to run in parallel. See notes here https://github.com/mrtazz/simplenote.py/commit/60b0f7b1d190f5e299a059a3a9394ab01a31dd62

Getting tests to pass consistently has been pretty impossible. See the history on [test_simplenote.py](https://github.com/mrtazz/simplenote.py/commits/master/tests/test_simplenote.py)

**Comment by sickmartian** [comment]
Hi Again!

It's a shame about the Travis tests, but the problems I reference to are not related to running concurrently, they happen on a single instance test.
What happens is that the class does a request when it's instantiated to authenticate, so on each test the setup section is creating the instance, and simplenote starts rejecting the requests because of that (Like on the second screenshot, after a moment all tests start giving back errors).

Having a single shared instance between the tests did the trick of solving that.

**Comment by atomicules** [comment]
Ok, I really will try to find time to look over this sometime this week.

**Comment by atomicules** [comment]
Have started looking at this, I promise, just busy. Totally agree about the multiple instances - strange as I'd never noticed that before, well spotted! I'm just looking into whether we'd be better off setting up the instance in a `setUpClass`.

**Comment by atomicules** [comment]
Hi, so I've merged this in and closed this pull request out. Unfortunately I've had to undo some of the work you did as it was causing tests to fail when I ran the tests - I've put a lot of comments explaining my actions in the commit above.

It may well be that I have to re-visit some of what you did as I review the Python 3 pull request, but certainly under 2.7.9 I couldn't get the tests to pass per the original pull request.

Anyway, thanks very much for spotting the multiple instance issue in the first place and making the pull request.

**Pull request merged**
